export const dayName = (string)=> {
  const date = new Date(string);
  return date.toLocaleDateString('en', { weekday: 'short' }); 
}

export const weatherState = {
  0: 'Clear sky',
  1: 'Mainly clear',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog and depositing rime fog',
  48: 'Fog and depositing rime fog',
  51: 'Drizzle: Light intensity',
  53: 'Drizzle: Moderate intensity',
  55: 'Drizzle: Dense intensity',
  56: 'Freezing Drizzle: Light intensity',
  57: 'Freezing Drizzle: Dense intensity',
  61: 'Rain: Slight intensity',
  63: 'Rain: Moderate intensity',
  65: 'Rain: Heavy intensity',
  66: 'Freezing Rain: Light intensity',
  67: 'Freezing Rain: Heavy intensity',
  71: 'Snow fall: Slight intensity',
  73: 'Snow fall: Moderate intensity',
  75: 'Snow fall: Heavy intensity',
  77: 'Snow grains',
  80: 'Rain showers: Slight intensity',
  81: 'Rain showers: Moderate intensity',
  82: 'Rain showers: Violent intensity',
  85: 'Snow showers: Slight intensity',
  86: 'Snow showers: Heavy intensity',
  95: 'Thunderstorm: Slight or moderate',
  96: 'Thunderstorm with slight hail',
  99: 'Thunderstorm with heavy hail'
};
export const weatherStateImages = {
  0: 'https://developer.accuweather.com/sites/default/files/01-s.png',
  1: 'https://developer.accuweather.com/sites/default/files/02-s.png',
  2: 'https://developer.accuweather.com/sites/default/files/08-s.png',
  3: 'https://developer.accuweather.com/sites/default/files/11-s.png',
  45: 'https://developer.accuweather.com/sites/default/files/11-s.png',
  48: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  51: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  53: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  55: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  56: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  57: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  61: 'https://developer.accuweather.com/sites/default/files/18-s.png',
  63: 'https://developer.accuweather.com/sites/default/files/18-s.png',
  65: 'https://developer.accuweather.com/sites/default/files/18-s.png',
  66: 'https://developer.accuweather.com/sites/default/files/26-s.png',
  67: 'https://developer.accuweather.com/sites/default/files/26-s.png',
  71: 'https://developer.accuweather.com/sites/default/files/22-s.png',
  73: 'https://developer.accuweather.com/sites/default/files/22-s.png',
  75: 'https://developer.accuweather.com/sites/default/files/22-s.png',
  77: 'https://developer.accuweather.com/sites/default/files/22-s.png',
  80: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  81: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  82: 'https://developer.accuweather.com/sites/default/files/12-s.png',
  85: 'https://developer.accuweather.com/sites/default/files/22-s.png',
  86: 'https://developer.accuweather.com/sites/default/files/22-s.png',
  95: 'https://developer.accuweather.com/sites/default/files/15-s.png',
  96: 'https://developer.accuweather.com/sites/default/files/15-s.png',
  99: 'https://developer.accuweather.com/sites/default/files/15-s.png'
}